version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
        enviroment:
          PGHOST: 127.0.0.1
          PGUSER: quantified-self
          NODE_ENV: test
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: quantified-self
          POSTGRES_DB: qs_database_test

    working_directory: ~/quantified-self

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npx nyc jest --passWithNoTests --forceExit
       - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
